kind: Secret
ansible_user: ENC[AES256_GCM,data:BRIHFXCKzQ==,iv:EyXMLJGNfyrmXypsMdYGfiQEwNiHd6svO/6LlK0Xizo=,tag:OBUIY/Vn6BfeFE6cbGDSZQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Mh934M1WYH7I,iv:I/nM0aCwVwoPLtH78YlHJa96bO53WhVfstDFmtbe8zg=,tag:4XpUAtyaRYdAKdtsqnY8aQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQlgra0NkQ1NVaGpTd2lM
            MzZFL2lZSXFwNUNuZTZBN3BjUnZodFJmVkUwCmNJeE9uSU1iaUh4MTZPazZCK0k4
            dWhBVGhjTzdwa3ZLdXpaT3BTLzI3WDQKLS0tIG9oZ2dMWklpQ0F2S28rSUVISUho
            YldGazhlTkdranA1eE1SVWRpYXF3cUkKDmTYETji5UGcGhxethVqWtUk1Z6ID9fb
            zNOHlLe1JKu/W03YMePPntU2gN3DUtm2PErtDYv14BjyKoI3NAlQGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-19T11:27:43Z"
    mac: ENC[AES256_GCM,data:lv2NxCUb9Hm4VvH6dxCH3HS2C2EO6GQnvrG3vHSNudvimJ5T7hzFWYCwrbSsH/KcoBuAMcaGo4S7LPN0rXuFQxWdVIJ6WzvNKOQNNpqV2t1lMA+Q9r+FyGpectkjnztfFzvAZWyZIqnEgCKTc9CD9YzH7tE28nV3nJv1YWo1GZQ=,iv:20bSNpRyCbyr+B3giOU6X8zvgMT/dycGDHSx7fU9xCY=,tag:yYIkV9cSR3IEpXBYgZ3Zqw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
