kind: Secret
ansible_user: ENC[AES256_GCM,data:EStgzp0mJA==,iv:K8imu0wqd018mbqpSnmFj3nG0IPEZ+1qgipHOyIz5tg=,tag:bdjrwyq59HRblgqXo73hNA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:UtOTA+4jQdbj,iv:kngPn81CgsGei67TQiW2SzXAq5vG12l6jwyQ9Jc1mbo=,tag:CKn+4dcXpRUOEOKeEiO+/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSmc0c1BLaEV6ei8xTk9R
            QjgzbitUclluakNGSXJ2THMwa24yc2hTSzBnCmQ1akMvZU5nWUo0eTNnRndQWjdx
            T1VVNlBwQUNsR0xBRXdBOVhKK0JxMjgKLS0tIHJteW9XZG9Tb1BQK0N3SDBFcVFu
            RjRqVXdSRktqcjZXTlQrZlZEL01FL2MKKOSq7aaJicvtspthKIXWVo/tpHBvbxRN
            s+zfFQrwpmxVos9bzNBbosMNFQ2D7IfaJOpjsHhnI+0sdm1OgCIMnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-09T16:08:55Z"
    mac: ENC[AES256_GCM,data:+MKCkt4aJ0XrbymvFWfxEWd5wIpgDm5IOhAy5fKgxoNbloWucfcq4/N9BrdqgGBwj1dNmhk2ri0+NMcbs+/UhOfHNftzDVz1OU2KBPOYDXZeUqACOvE9PaSXd32zugTtq+Rvv1tDRgTa255Y4KrKkeiEyvvchiOP/P/h2uEv5xo=,iv:8HRgUQ6ivcMS+rr38lZCpeDsAdHxR86QeVUaSDzA3YU=,tag:dZv5UUXjAJE3N5c14JBY1w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
