# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:FS0C3KS1tn1Wm2m1rAdjqS8+byEzzplF9dydjbGzayyofzeAjkYH6Q==,iv:ISuN4VSv0mQygJnZ4w5mTR1lZRvOayw4N6rA9QHb1n4=,tag:iVmUvK9HTIkWfn7urtuCPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QnR4SzlLckttNVpLK0pw
            ZTJjR25vYzhQNDgxWUNmL3NVQ1R2RTRjd0dnCmZFQ3BsSWE4alFJeTh4SUYxSEJH
            NG45Y01PalJyQVNVZFo2Vzg0ck1vREEKLS0tIGtmRFVTczlCWS85Q2wzSVhQei9x
            dlA1V2NuWWVOQ09NSlhJQ1pKTE1xKzAK/cMg6pxYanUVV5hIHH3mO7d2g3zuoPhY
            3wtSipkXeXTGpnKb/kTTc01VX4UC9ax+ogGMOK1+YQ8gj9QlIgOj6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-19T11:27:43Z"
    mac: ENC[AES256_GCM,data:AM0iq6up+uDKyAJQd/nPiukaIAH+MyIYRJRKn/1+/3UWKac37HNIjLjV/2ymqKUazqHyct5SUTSmz9Wj6u684bUu5n5IX+iA+6EanEwyp5b7FKTObVXgHzmn0l4yMGHgNcfp/gji1lSzEWlMMwTk7FWGJrIMN4mlqdxPl/jNWr0=,iv:RNYnVP7EbKFB5Oa+3HZ8W2CTRSkU9YRQhlzuoJ5lTdU=,tag:fP4P+aca80QmGRtlYB5lPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
